# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f759a47ba3d7acc5d0c841723690e44e40035526b22dda49988b3a198864adbc6fcdd5b2c066cdb545dd87ce55d340317206085c31566fb6dca9f4b2b31f4e22

test:
  secret_key_base: 5f6be0b7eb39c2ded79cf7ec4128b032d51fe4723a07dbf1a051253838eab5870a1ae6eea6eef123f5dbf71cf67608a3571bad44ea2131ef0e0209b8b3597ccb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
